USE LAB_TBD
GO

CREATE TABLE CALENDAR (CALE_ID INT NOT NULL, CALE_FECHA DATE NOT NULL, CALE_ANIO INT NOT NULL, CALE_MES TINYINT NOT NULL, CALE_DIA TINYINT NOT NULL, CALE_MES_DESC VARCHAR(20) NULL)
GO

DECLARE @FECHA DATE = '20230101'

;WITH
CTE
AS
(
	SELECT 1 AS CALE_ID, @FECHA AS CALE_FECHA
	UNION ALL
	SELECT CALE_ID + 1, DATEADD(D, 1, CALE_FECHA) AS CALE_FECHA
	FROM CTE
	WHERE CALE_FECHA < '20231231'
)
INSERT INTO CALENDAR
SELECT CALE_ID, CALE_FECHA, YEAR(CALE_FECHA) AS CALE_ANIO, MONTH(CALE_FECHA) AS CALE_MES, DAY(CALE_FECHA) AS CALE_DIA, NULL
FROM CTE
OPTION (MAXRECURSION 0)

--CONSTRAINT
-- PRIMARY KEY
-- UNIQUE 
-- FOREIGN KEY 
-- CHECK
-- DEFAULT

SELECT * FROM CALENDAR

-- PRIMARY KEY
ALTER TABLE CALENDAR ADD CONSTRAINT PK_CALENDAR_CALE_ID PRIMARY KEY (CALE_ID)
GO

INSERT INTO CALENDAR VALUES(1, '20230101', 2023, 1, 1, NULL)
-- Violation of PRIMARY KEY constraint 'PK_CALENDAR_CALE_ID'. Cannot insert duplicate key in object 'dbo.CALENDAR'. The duplicate key value is (1).

ALTER TABLE CALENDAR DROP CONSTRAINT PK_CALENDAR_CALE_ID
GO

INSERT INTO CALENDAR VALUES(1, '20230101', 2023, 1, 1, NULL)

SELECT * FROM CALENDAR WHERE CALE_ID = 1


-- UNIQUE 
DELETE FROM CALENDAR  WHERE CALE_ID = 1

ALTER TABLE CALENDAR ADD CONSTRAINT UK_CALENDAR_CALE_FECHA UNIQUE (CALE_FECHA)
GO

INSERT INTO CALENDAR VALUES(1, '20230101', 2023, 1, 1, NULL)

INSERT INTO CALENDAR VALUES(1, '20230101', 2023, 1, 1, NULL)
--Violation of PRIMARY KEY constraint 'PK_CALENDAR_CALE_ID'. Cannot insert duplicate key in object 'dbo.CALENDAR'. The duplicate key value is (1).

INSERT INTO CALENDAR VALUES(366, '20230101', 2023, 1, 1, NULL)
--Violation of UNIQUE KEY constraint 'UK_CALENDAR_CALE_FECHA'. Cannot insert duplicate key in object 'dbo.CALENDAR'. The duplicate key value is (2023-01-01).

-- FOREIGN KEY
INSERT INTO CALENDAR VALUES(366, '20240101', 2024, 13, 1, NULL)
SELECT * FROM CALENDAR 

DROP TABLE MES
CREATE TABLE MES (ID TINYINT PRIMARY KEY)
GO

INSERT INTO MES VALUES (1), (2), (3), (4), (5), (6), (7), (8), (9), (10), (11), (12)

ALTER TABLE CALENDAR ADD CONSTRAINT FK_CALENDAR_CALE_MES FOREIGN KEY (CALE_MES) REFERENCES MES (ID)
GO
-- Column 'MES.ID' is not the same data type as referencing column 'CALENDAR.CALE_MES' in foreign key 'FK_CALENDAR_CALE_MES'.

DELETE FROM CALENDAR WHERE CALE_ID = 366

ALTER TABLE CALENDAR ADD CONSTRAINT FK_CALENDAR_CALE_MES FOREIGN KEY (CALE_MES) REFERENCES MES (ID)
GO

INSERT INTO CALENDAR VALUES(366, '20240101', 2024, 13, 1, NULL)
-- The INSERT statement conflicted with the FOREIGN KEY constraint "FK_CALENDAR_CALE_MES". The conflict occurred in database "LAB_TBD", table "dbo.MES", column 'ID'.

-- CHECK

INSERT INTO CALENDAR VALUES(366, '20240101', 2021, 12, 50, NULL)
SELECT * FROM CALENDAR WHERE CALE_ID = 366

UPDATE CALENDAR SET CALE_ANIO = -2000
SELECT * FROM CALENDAR
UPDATE CALENDAR SET CALE_ANIO = YEAR(CALE_FECHA)
SELECT * FROM CALENDAR

ALTER TABLE CALENDAR ADD CONSTRAINT CK_CALENDAR_CALE_ANIO CHECK (CALE_ANIO = YEAR(CALE_FECHA))

INSERT INTO CALENDAR VALUES(367, '20240102', 2021, 12, 50, NULL)
--The INSERT statement conflicted with the CHECK constraint "CK_CALENDAR_CALE_ANIO". The conflict occurred in database "LAB_TBD", table "dbo.CALENDAR".
INSERT INTO CALENDAR VALUES(367, '20240102', -2021, 12, 50, NULL)
--The INSERT statement conflicted with the CHECK constraint "CK_CALENDAR_CALE_ANIO". The conflict occurred in database "LAB_TBD", table "dbo.CALENDAR".
INSERT INTO CALENDAR VALUES(367, '20240102', 0, 12, 50, NULL)
--The INSERT statement conflicted with the CHECK constraint "CK_CALENDAR_CALE_ANIO". The conflict occurred in database "LAB_TBD", table "dbo.CALENDAR".

INSERT INTO CALENDAR VALUES(367, '20240102', 2024, 12, 50, NULL)

ALTER TABLE CALENDAR ADD CONSTRAINT CK_CALENDAR_CALE_MES CHECK (CALE_MES = MONTH(CALE_FECHA) AND CALE_DIA = DAY(CALE_FECHA))

UPDATE CALENDAR SET CALE_MES = MONTH(CALE_FECHA), CALE_DIA = DAY(CALE_FECHA)

ALTER TABLE CALENDAR ADD CONSTRAINT CK_CALENDAR_CALE_MES CHECK (CALE_MES = MONTH(CALE_FECHA) AND CALE_DIA = DAY(CALE_FECHA))

INSERT INTO CALENDAR VALUES(368, '20240103', 2024, 12, 12, NULL)
-- The INSERT statement conflicted with the CHECK constraint "CK_CALENDAR_CALE_MES". The conflict occurred in database "LAB_TBD", table "dbo.CALENDAR".

INSERT INTO CALENDAR VALUES(368, '20240103', 2024, 1, 3, NULL)
INSERT INTO CALENDAR VALUES(369, '20200229', 2020, 2, 29, NULL)
INSERT INTO CALENDAR VALUES(369, '20230229', 2023, 2, 29, NULL)

ALTER TABLE CALENDAR ADD CONSTRAINT CK_CALENDAR_CALE_MES CHECK (CALE_MES IN (SELECT ID FROM MES))
-- Subqueries are not allowed in this context. Only scalar expressions are allowed.

SELECT * FROM CALENDAR
UPDATE CALENDAR SET CALE_MES_DESC = 'InDriver'
UPDATE CALENDAR SET CALE_MES_DESC = DATENAME(MONTH, CALE_FECHA)
SELECT * FROM CALENDAR

ALTER TABLE CALENDAR ADD CONSTRAINT CK_CALENDAR_CALE_MES_DESC CHECK (CALE_MES_DESC = DATENAME(MONTH, CALE_FECHA))


-- DEFAULT

