CREATE TABLE CALENDARIO (ID INT PRIMARY KEY, FECHA DATE)
GO

;WITH
CTE
AS
(
	SELECT CONVERT(DATE, '20230101') AS FECHA
	UNION ALL
	SELECT DATEADD(D, 1, FECHA) AS FECHA
	FROM CTE
	WHERE FECHA < '20230131'
)
INSERT INTO CALENDARIO
SELECT ROW_NUMBER() OVER (ORDER BY FECHA ASC), FECHA
FROM CTE

SELECT * FROM CALENDARIO

-- 1. PLANTILLA
DECLARE <NOMBRE> CURSOR
	FOR
		<CONSULTA>
OPEN <NOMBRE>
WHILE @@FETCH_STATUS = 0
BEGIN
	FETCH NEXT FROM <NOMBRE>
END 
CLOSE <NOMBRE>
DEALLOCATE <NOMBRE>

-- 2. Implementar cursor para recorrer los dias del mes de enero 2023
DECLARE Registros_Enero CURSOR
	FOR
		SELECT FECHA FROM CALENDARIO WHERE FECHA BETWEEN '20230101' AND '20230131'
OPEN Registros_Enero
FETCH NEXT FROM Registros_Enero
CLOSE Registros_Enero
DEALLOCATE Registros_Enero

-- 3. Implementar cursor para recorrer los dias del mes de enero 2023
DECLARE Registros_Enero CURSOR
	FOR
		SELECT FECHA FROM CALENDARIO WHERE FECHA BETWEEN '20230101' AND '20230115'
OPEN Registros_Enero
FETCH NEXT FROM Registros_Enero
WHILE @@FETCH_STATUS = 0
BEGIN
	FETCH NEXT FROM Registros_Enero
END 
CLOSE Registros_Enero
DEALLOCATE Registros_Enero

-- 4. Implementar cursor para recorrer los dias del mes de enero 2023
DECLARE @FECHA DATE, @MES TINYINT

DECLARE Registros_Enero CURSOR
	FOR
		SELECT FECHA 
		FROM CALENDARIO WHERE FECHA BETWEEN '20230101' AND '20230115'
OPEN Registros_Enero
FETCH NEXT FROM Registros_Enero
INTO @FECHA
WHILE @@FETCH_STATUS = 0
BEGIN
	SELECT @FECHA, YEAR(@FECHA), MONTH(@FECHA)

	FETCH NEXT FROM Registros_Enero
	INTO @FECHA
END 
CLOSE Registros_Enero
DEALLOCATE Registros_Enero

------
DECLARE @FECHA DATE, @MES TINYINT

;WITH
CTE
AS
(
	SELECT FECHA 
	FROM CALENDARIO WHERE FECHA BETWEEN '20230101' AND '20230115'
)
SELECT * INTO #TEMP FROM CTE

DECLARE Registros_Enero CURSOR
	FOR 
		SELECT * FROM #TEMP
OPEN Registros_Enero
FETCH NEXT FROM Registros_Enero
INTO @FECHA
WHILE @@FETCH_STATUS = 0
BEGIN
	SELECT @FECHA, YEAR(@FECHA), MONTH(@FECHA)

	FETCH NEXT FROM Registros_Enero
	INTO @FECHA
END 
CLOSE Registros_Enero
DEALLOCATE Registros_Enero


-- 5. TIPOS DE CURSORES
-- A) STANDARD: SOLO AVANCE
-- B) SCROLL