-- CONEXION B
/*
SET TRANSACTION ISOLATION LEVEL
[READ COMMITTED], [READ UNCOMMITTED], [REPEATABLE READ], [SERIALIZABLE], [SNAPSHOT], [READ COMMITTED SNAPSHOT]
*/

--TEST 1 - BLOQUEOS (READ COMMITED - LECTURAS CONFIRMADAS)
SET TRANSACTION ISOLATION LEVEL 
READ COMMITTED 

SELECT * FROM PRODUCT --BLOQUEO TABLA
SELECT * FROM PRODUCT WHERE ID = 10
SELECT * FROM PRODUCT WHERE ID = 11
SELECT * FROM PRODUCT WHERE ID = 42
SELECT * FROM PRODUCT WHERE ID = 72 --BLOQUE REGISTRO

INSERT INTO PRODUCT VALUES (101, 'PRODUCTO 101')
UPDATE PRODUCT SET NAME = NAME + ' UPDATE' WHERE ID = 11

SELECT * FROM ORDER_DETAIL

DBCC USEROPTIONS

--TEST 2 - ISOLATION LEVEL READ UNCOMMITTED
SET TRANSACTION ISOLATION LEVEL 
READ UNCOMMITTED

SELECT * FROM PRODUCT
SELECT * FROM PRODUCT WHERE ID = 10
SELECT * FROM PRODUCT WHERE ID = 72
SELECT * FROM PRODUCT WHERE ID = 101

SELECT * FROM ORDER_DETAIL WHERE ID_ORDER = 1 AND ID = 1 -- LECTURAS SUCIAS

-- TEST 3 - ISOLATION LEVEL REPEATABLE READ
SET TRANSACTION ISOLATION LEVEL 
REPEATABLE READ

DBCC USEROPTIONS

SELECT * FROM PRODUCT
SELECT * FROM PRODUCT WHERE ID = 10

UPDATE PRODUCT SET NAME = NAME + ' UPDATE' WHERE ID = 10

SELECT * FROM PRODUCT

----

SELECT * FROM PRODUCT
SELECT * FROM PRODUCT WHERE ID = 10

UPDATE PRODUCT SET NAME = NAME + ' UPDATE' WHERE ID = 10
UPDATE PRODUCT SET NAME = NAME + ' UPDATE' WHERE ID = 11

SELECT * FROM PRODUCT

--TEST 4 - ISOLATION LEVEL SERIALIZABLE
SELECT * FROM PRODUCT 
INSERT INTO PRODUCT VALUES (9, 'PRODUCTO 9') -- BLOQUE
UPDATE PRODUCT SET NAME = NAME + ' UPDATE' WHERE ID = 72 -- BLOQUE
DELETE PRODUCT WHERE ID = 72 -- BLOQUE

INSERT INTO PRODUCT VALUES (9, 'PRODUCTO 9') 

INSERT INTO PRODUCT VALUES (99, 'PRODUCTO 9') 
UPDATE PRODUCT SET NAME = NAME + ' UPDATE' WHERE ID = 99
DELETE PRODUCT WHERE ID = 99

-- TEST 5 - ISOLATION LEVEL SNAPSHOT
SET TRANSACTION ISOLATION LEVEL 
SNAPSHOT

ALTER DATABASE TBD SET ALLOW_SNAPSHOT_ISOLATION ON

SELECT * FROM PRODUCT WHERE ID = 10

-----

BEGIN TRANSACTION
	SELECT * FROM PRODUCT WHERE ID = 10
COMMIT TRANSACTION
SELECT * FROM PRODUCT WHERE ID = 10