CREATE FUNCTION <uFN_Nombre>
(
	<Parametros obligatorios>
)
RETURNS <TIPO DE DATO DE RETORNO>
AS
BEGIN
	<INSTRUCCIONES>
	--RESTRICCIONES, NO SE PUEDE EJECUTAR SPS
	--NO SE PUEDEN CREAR TABLAS TEMPORALES LOCALES NI GLOBALES
	--NO SE PUEDE UTILIZAR INSERT, UPDATE, DELETE
	RETURN <VARIABLE RETORNO>
END
GO
