-- Merge

MERGE
	INTO PROVEEDOR_REPLICATE AS T -- tabla destino (Target)
	USING PROVEEDOR AS S --tabla/select (Source)
	ON S.ID = T.ID --AND S.COL2 = T.COL2 AND 

	WHEN NOT MATCHED --INSERTAR (LEFT)
		THEN 
			INSERT (ID, RAZON_SOCIAL)
			VALUES (S.ID, S.RAZON_SOCIAL)

	WHEN MATCHED --ACTUALIZAR (INNER)
		AND (T.RAZON_SOCIAL <> S.RAZON_SOCIAL)   
		THEN 
			UPDATE 
			SET RAZON_SOCIAL = S.RAZON_SOCIAL

	WHEN NOT MATCHED BY SOURCE --ELIMINAR (DELETE)
		THEN 
			DELETE

	--OUTPUT $ACTION, INSERTED.ID, DELETED.ID
;
