IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME = 'CALENDARIO_PC5' AND XTYPE = 'U')
	DROP TABLE CALENDARIO_PC5
GO

CREATE TABLE CALENDARIO_PC5 (CALE_CODIGO INT PRIMARY KEY, CALE_FECHA DATE NOT NULL)
GO

IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME = 'CALENDARIO_PC5_LOG' AND XTYPE = 'U')
	DROP TABLE CALENDARIO_PC5_LOG
GO

CREATE TABLE CALENDARIO_PC5_LOG (CALE_CODIGO INT NOT NULL, CALE_FECHA DATE NOT NULL, CALE_FECHA_LOG SMALLDATETIME DEFAULT GETDATE())
GO

;WITH
CTE
AS
(
	SELECT CONVERT(SMALLDATETIME , '20220101') AS FECHA
	UNION ALL
	SELECT DATEADD(DD, 1, FECHA) AS FECHA
	FROM CTE
	WHERE FECHA < '20221231'
)
INSERT INTO CALENDARIO_PC5 (CALE_CODIGO, CALE_FECHA)
SELECT CONVERT(INT, FECHA), FECHA 
FROM CTE
OPTION (MAXRECURSION 0)


select * from CALENDARIO_PC5


insert CALENDARIO_PC5  values(CONVERT(INT, CONVERT(SMALLDATETIME, '20230101')), CONVERT(SMALLDATETIME, '20230101'))

update CALENDARIO_PC5 
set cale_fecha = '20230102'
where cale_codigo = 44925

delete CALENDARIO_PC5 
where cale_codigo = 44925


insert CALENDARIO_PC5  values(44926, '20230101')


select CONVERT(SMALLDATETIME, '20230101')

insert CALENDARIO_PC5  values(CONVERT(INT, CONVERT(SMALLDATETIME, '20230101')), CONVERT(SMALLDATETIME, '20230101'))

SELECT  CONVERT(INT, CONVERT(SMALLDATETIME, '20230101'))

